version: "3.8"

services:
  db:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$AUTH_PASSWORD
      - MYSQL_DATABASE=$AUTH_DATABASE
    ports:
      - $AUTH_PORT:$AUTH_PORT
    volumes:
      - database:/var/lib/mysql
  auth-service:
    build: "./auth-service"
    env_file: ./.env
    volumes:
      - ./auth-service/src:/app/src
    ports:
      - $PORT:$PORT
    depends_on:
      - db
  messages-service:
    build: "./messages-service"
    env_file: ./.env
    volumes:
      - ./messages-service/src:/app/src
    ports:
      - $MESSAGES_PORT:$MESSAGES_PORT
    depends_on:
      - messages-db
  java-db:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$JAVA_DB_PASSWORD
      - MYSQL_DATABASE=$JAVA_DATABASE
    ports:
      - $JAVA_DB_EXTERNAL_PORT:$JAVA_DB_INTERNAL_PORT
    volumes:
      - java-db:/var/lib/mysql
  messages-db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - $MONGO_PORT:$MONGO_PORT
    volumes:
      - messages-db:/data/db
  mongo-admin:
    image: mongo-express
    env_file: ./.env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=messages-db
    ports:
      - 8999:8081
    depends_on:
      - messages-db
  auth-mysql-admin:
    image: phpmyadmin
    restart: always
    env_file: ./.env
    ports:
      - 3002:80
    environment:
      - PMA_PORT=$AUTH_PORT
      - PMA_HOST=$AUTH_HOST
  java-mysql-admin:
    image: adminer
    restart: always
    env_file: ./.env
    ports:
      - 3001:8080
    environment:
      - ADMINER_DEFAULT_SERVER=$JAVA_HOST
volumes:
  database:
  java-db:
  messages-db:
